import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Logout from "@/components/Logout";
import LoginButton from "@/components/LoginButton";

import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerSession(authOptions);
  console.log(session);
  console.log("session");
  return (
    <html lang="en"  data-theme="mytheme">
      <body className={inter.className}>
        <div style={{ display: "flex", flexDirection: "column" }}>
        <div className="navbar bg-neutral text-white">
  <div className="flex-none">

  </div>
  <div className="flex-1">
    <Link className="btn btn-ghost text-xl" href={"/posts"}>Posts</Link>

    <Link className="btn btn-ghost text-xl" href={"/albums"}>Albums</Link>
  </div>

  {session ?
  <div className="flex-none">
    <p className="me-3 text-gray-400 text-sm">Connecté en tant que <span className="font-bold text-white text-base">{session.user.name}</span></p>
    <Logout />
  </div>
    :
    <div className="flex-none">
     <LoginButton />
    </div>
  }
</div>
          {children}
        </div>
      </body>
    </html>
  );
}